### ISSUE TITLE
When AUR updates available, no notification are shown and it pass

### ISSUE THREAD

**Issue by freed00m** [Chrysostomus/update-notifier#1]
Hi, I I see yaourt is called within the script version 0.1-1.

```
eval yaourt -Qua | grep "aur" 
```

does actualy works and it shows what is available for upgrade.

For regular pacman update the script works as expected.

**Comment by Chrysostomus** [comment]
Yes, this is intended behaviour, designed to reduce stress of unnecessary polling on aur servers. It checks for aur updates only if there are regular uodates as well. 

Is this a feature request for notification to trigger also when there are only aur updates?

I take it that

**Comment by freed00m** [comment]
@Chrysostomus That would be a very nice feature, I thought it was a  bug cause Octopi-tray and Pamac-tray both pull from aur every time they check for update. 

The default behavior could remain the same, but perhaps optional argument?

**Comment by Chrysostomus** [comment]
Nah, too complicated for now, I'm busy. It now notifies for aur only updates now though, as originally requested.
