### ISSUE TITLE
Why 'update-check' does exist?

### ISSUE THREAD

**Issue by cubanpit** [Chrysostomus/update-notifier#14]
It is not clear to me why the script `update-check` exists and/or why it is split from the others.
It seems like a useful script that can be called from `update-notifier` with minor integration work, but at the moment it is standalone and it is not described in the readme file.

I'm opening this mainly because `update-notifier` does not respect ignored AUR packages, while `update-check` does, and I'm interested in this feature.

**Comment by Chrysostomus** [comment]
It is for the gnome edition. It is used for the update-notifier shell extension.

**Comment by cubanpit** [comment]
Probably the best solution to handle multiple similar script is to create some "functions" file with most common operations, I can help to sketch something similar.
