### ISSUE TITLE
Don't use yay -Syua

### ISSUE THREAD

**Issue by Morganamilo** [Chrysostomus/update-notifier#16]
`yay -Syua` will lead to partial upgrades. I'm not sure if you're using -a because you want to upgrade just AUR packages or out of habit from yaourt. Whichever one you intend to do, there are examples of both in the yay man page, as well as documentation for -a/--aur.

See also https://github.com/Jguer/yay/pull/624

(And if you happen to be a wiki maintainer could you also make the fix here https://wiki.manjaro.org/index.php/Arch_User_Repository)

**Comment by Chrysostomus** [comment]
Thanks, it is indeed there by mistake. I'll fix it soon.
