### ISSUE TITLE
disable update-notifier during live-session

### ISSUE THREAD

**Issue by hphilm** [Chrysostomus/update-notifier#7]
On a live-session most likely there are no **pacman DBs** there. Also it would be good to disable the update-notifier completely during the live-session, when possible. Example: https://github.com/manjaro/iso-profiles/commit/6a892eee098e9772dc07c508bf67ad2c159cb84e

**Comment by Chrysostomus** [comment]
Good idea. Currently the script doesn't provide its own autostart mechanism. Are you suggesting that we check on script level if the session is a live one? One option would be to to test for the existence of pacman database, and look for updates only if one exists. Is there a better way to test if it is running in a live session?

**Comment by hphilm** [comment]
In **Manjaro-Hello** we check for `"live_path": "/run/miso/bootmnt/manjaro",`. However `"live_path": "/run/miso/bootmnt",` would be enough.

**Comment by Chrysostomus** [comment]
Okay, I'll add the check

**Comment by Chrysostomus** [comment]
Okay, I'll add

```
if ! $(ping -c 3 google.com >> /dev/null 2>&1); then
	exit
elif [[ -e /run/miso/bootmnt ]]; then
	exit
fi
```

This should also hopefully get rid of the false positives in the kernel checking.
