### ISSUE TITLE
Check if update command was successful

### ISSUE THREAD

**Issue by kainonergon** [Chrysostomus/update-notifier#9]
When choosing "update now" from notification, terminal opens, update command is executed and then terminal closes at once. There is no message if update was successful or not. Maybe in case of success send another notification and in case of failure leave the terminal open? Not sure how to do that though.

**Comment by Chrysostomus** [comment]
One way would be to just add read command after it, so terminal stays open until the user presses enter

**Comment by kainonergon** [comment]
Yes, it would do, but it might be annoying to colse the terminal if update went OK. Maybe somehow check exit status of update command and add read command only if update failed?

**Comment by kainonergon** [comment]
Maybe this https://github.com/Chrysostomus/update-notifier/pull/10

**Comment by kainonergon** [comment]
This might be better https://github.com/Chrysostomus/update-notifier/pull/11
